#' transfer_portal()
#'
#' The Harly Fund Transfer Environment
#'
#' @export
transfer_portal <- function() {
  options(warn=-1)
  cat("\nHello, I am Hubby and Welcome to the Joint Op Net Array Technology Heritage And Non-Script Unit Content Key Service  \nor simply: J.O.N.A.T.H.A.N.S.U.C.K.S.\nI will be your service bot today :D \nWe at J.O.N.A.T.H.A.N.S.U.C.K.S will handle all transfers related to the Harly Fund.")
  cat("\n\nQuiz time! To gain entry to the transfer portal, get the right answer to this security question:")
  cat("\n---> What KDA would Jonathan's Hecarim be riding without Frederik's Zilean?  ")
  answer <- readline()
  if(answer != "0.4") {
    cat("\n-------------------------------------------------------------------\n")
    cat("\nYour answer is clearly not correct. (hint: you should use \".\" as decimal separator)")
  } else {
    cat("\n-------------------------------------------------------------------\n")
    cat("\nGood answer!\n")
    cat("\nMoney transfers via this process guarantees utmost security, and ensures that necessary \n   permitions have been obtained for your transfer.\n")
    Sys.sleep(2)
    cat("\n-------------------------------------------------------------------\n")
    if("readmeagainplz.csv" %in% list.files()){
      cat("\nI am sorry, but only one transfer request is allowed per week.")
    } else{
      cat("\n---> What is your name?   ")
      name <- readline(prompt = "")
      cat("\n-------------------------------------------------------------------\n")
      cat(paste("\nHello ",name,", it is a pleasure to meet you. ", sep=""))
      Sys.sleep(1)
      cat("\n\n---> What can I help you with today?   ")
      cat("\nEnter <1> if you wish to make a transfer to Frederik.")
      cat("\nEnter <2> if you wish to collect money owed from Frederik\n")
      transfer.type <- readline(prompt = "")
      if(transfer.type == 1) {
        cat("\nYou have selected to make a transfer to Frederik.\n")
        cat("\n-------------------------------------------------------------------\n")
        }
      if(transfer.type == 2) {
        cat("\nYou have selected to collect money owed from Frederik.\n")
        cat("\n-------------------------------------------------------------------\n")
        }
      if(!(transfer.type %in% c(1,2))) cat("\nIt appears that you are an absolute moron, and have failed to choose one of two numbers. \n\nProcess is terminated.")
      if(transfer.type == 2){
        Sys.sleep(1)
        cat("\n---> What amount of moneyz are you owed?   ")
        amount <- as.numeric(readline(prompt = ""))
        cat("---> What is your bank account registration number?   ")
        regi <- as.numeric(readline(prompt=""))
        cat("---> What is your bank account number?   ")
        acc <- as.numeric(readline(prompt = ""))+1000
        while(!(nchar(trunc(regi))==4 & !is.na(regi) & !is.na(acc) & !is.na(amount))) {
          Sys.sleep(1)
          cat("\n-------------------------------------------------------------------\n")
          cat("\nI cannot seem to validate the transfer amount and/or the bank account information you have supplied - sure you did not have a stroke while typing?")
          cat("\n\nTransfer amount must be <drum roll>.. a NUMBER. \nAccount details must be <drum roll>.. NUMBERS.")
          cat("\n\nLet us try again..")
          cat("\n---> What amount of moneyz are you owed?   ")
          amount <- as.numeric(readline(prompt = ""))
          cat("---> What is your bank account registration number?   ")
          regi <- as.numeric(readline(prompt=""))
          cat("---> What is your bank account number?   ")
          acc <- as.numeric(readline(prompt = ""))
        }
        if(amount > 5000) {
          amount = 5000
          cat("\n\n\n Your attempt at stealing Frederik's moneyz has been prevented. Your asking amount has been set to max limit of 5000 moneyz")
        }
        cat(paste("---> Are you sure that you want to claim",amount,"moneyz? (yes / no)   "))
        answer <- readline(prompt = "")
        if(answer == "yes") {
          mailR::send.mail(
            from = "imgoej@gmail.com",
            to = "imgoej@gmail.com",
            subject = "Transaction notice (IMPORTANT!)",
            body = paste("A transfer request of ",amount," USD (",round(amount*6.570765)," DKK) has been submitted by: \n",name,"\n\nRecipient account details are: \nreg.:",regi,"\nacc.:",acc,"\n\nTo stop this transfer, go to your personal banking app.", sep = ""),
            smtp = list(host.name = "smtp.gmail.com", port = 465,
                        user.name = "imgoej@gmail.com",
                        passwd = "_Denisovan8", ssl = TRUE),
            authenticate = TRUE,
            send = TRUE
          )
          write.csv("Jonathan likes to buy and sniff used panties", "readmeagainplz.csv", row.names = F)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")
          Sys.sleep(0.1)
          cat("\n--")

          cat("\n-------------------------------------------------------------------\n")
          cat(paste("\nYour transfer request of ",amount," USD (",round(amount*6.570765)," DKK) has been submitted to Frederik.",sep = ""))
          cat(paste("\nMoneyz are sent to: \nreg.:",regi,"\nacc.:",acc))
          cat("\n\nA notification has been sent to Frederik, giving him one hour to reject this transfer. \nAfter one hour, this request is processed automatically.")
        } else {
          cat("\n-------------------------------------------------------------------\n")
          cat("\nIt seems that you either could not figure out how to enter \"yes\" or chose \"no\". Process is terminated.")}
      }
      if(transfer.type == 1){
        cat("\nI am sorry, but Frederik has temporarily deactivated this option. \nTo explain, Frederik has cited \"I don't want your fucking moneyz\"")
      }}
  }


  cat("\n\nAll there is left to say is: have a nice day!\n")
  options(warn=0)
}
